backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog" 
public_folder: "/assets/blog"  
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Imagem do Post", name: "image", widget: "image" }
      - { label: "Imagem Alt", name: "imageAlt", widget: "string" }
      - { label: "Texto", name: "body", widget: "markdown" }
